# Generated by Django 2.2.2 on 2019-06-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
