# Generated by Django 2.2.2 on 2019-06-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='grade',
            new_name='income',
        ),
        migrations.AddField(
            model_name='member',
            name='job',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
